"""
Alembic migration environment.
===============================

This file is executed every time you run an Alembic command (upgrade,
downgrade, revision, etc.). It configures:

  1. Which database to connect to (from DATABASE_URL env var or default).
  2. Which models to compare against (Base.metadata from your models.py).
  3. How to run migrations (online mode for normal use, offline mode for
     generating raw SQL scripts).

You should rarely need to edit this file. The main reasons to touch it:
  • Adding custom type comparators (e.g., for ltree, TSVECTOR)
  • Excluding certain tables from autogeneration
  • Adding pre/post migration hooks

How autogenerate works:
───────────────────────
When you run `alembic revision --autogenerate -m "description"`, Alembic:
  1. Connects to the database and reads the CURRENT schema.
  2. Reads your models.py and computes the DESIRED schema.
  3. Diffs them and generates a migration script with the changes.

This means your database must be running and accessible when you
autogenerate. The Docker container must be up.
"""

import os
import sys
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from alembic import context

# ── Make the app package importable ──
# Alembic runs from the project root. We need Python to find `app/`.
# This adds the project root to sys.path so `from app.models import Base` works.
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

# ── Import your models ──
# This import does two critical things:
#   1. Imports Base, which holds the metadata (table definitions).
#   2. Triggers the import of ALL model classes (User, Book, BookEntry, etc.),
#      which registers them on Base.metadata. Without this, Alembic would
#      see an empty metadata and generate no tables.
from app.models import Base

# ── Alembic Config object ──
# Provides access to values in alembic.ini.
config = context.config

# ── Logging setup ──
# Interprets the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ── Target metadata ──
# This is what Alembic compares the database against during autogenerate.
# It contains all your table definitions, indexes, constraints, etc.
target_metadata = Base.metadata

# ── Database URL ──
# Priority: DATABASE_URL env var > alembic.ini sqlalchemy.url
# This ensures the same URL used by your app is used by migrations.
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://postgres:localpassword@localhost:5432/book_platform",
)
config.set_main_option("sqlalchemy.url", DATABASE_URL)


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.

    This generates SQL scripts without connecting to the database.
    Useful for: reviewing migrations before applying, generating SQL
    for a DBA to run manually, or environments where direct DB access
    isn't available.

    Usage: alembic upgrade head --sql > migration.sql
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.

    This connects to the database and applies migrations directly.
    This is the normal mode for development and deployment.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            # ── Compare types ──
            # Without this, Alembic ignores column type changes (e.g.,
            # changing String(50) to String(100)). With it enabled,
            # type changes show up in autogenerated migrations.
            compare_type=True,
            # ── Compare server defaults ──
            # Detects changes to server_default values.
            compare_server_default=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
