"""initial schema v4

Revision ID: 0001
Revises: None
Create Date: 2026-03-22

This is the foundational migration that creates the entire v4 schema.
It was written by hand (not autogenerated) to ensure the exact DDL
matches what was validated by the test suite (66 tests passing).

What this migration creates:
  • 1 extension: ltree
  • 3 enums: contributor_role_enum, reading_status_enum, activity_type_enum
  • 13 tables: users, follows, contributors, books, book_contributors,
    reading_statuses, book_entries, lists, list_items, comments, likes,
    reposts, timeline
  • 21 indexes (B-tree, GIN, GiST, partial, covering)
  • CHECK constraints, UNIQUE constraints, FK constraints (CASCADE/RESTRICT/SET NULL)

To apply: alembic upgrade head
To reverse: alembic downgrade -1  (drops everything — use with extreme caution)
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, TSVECTOR

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create the entire v4 schema."""

    # ── Extensions ──
    op.execute("CREATE EXTENSION IF NOT EXISTS ltree")

    # ══════════════════════════════════════════════════════════════════════
    # 1. USERS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "users",
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("username", sa.String(30), nullable=False),
        sa.Column("email", sa.String(254), nullable=False),
        sa.Column("password_hash", sa.String(256), nullable=False),
        sa.Column("avatar_url", sa.String(2048), nullable=True),
        sa.Column("location", sa.String(100), nullable=True),
        sa.Column(
            "follower_count", sa.Integer, server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "following_count", sa.Integer, server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_deleted", sa.Boolean, server_default=sa.text("false"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        "ix_users_active_username",
        "users",
        ["username"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "ix_users_active_email",
        "users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("is_deleted = false"),
    )

    # ══════════════════════════════════════════════════════════════════════
    # 2. FOLLOWS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "follows",
        sa.Column("follower_id", UUID(as_uuid=True), nullable=False),
        sa.Column("followed_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
        sa.ForeignKeyConstraint(["follower_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["followed_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.CheckConstraint("follower_id != followed_id", name="ck_no_self_follow"),
    )
    op.create_index("ix_follows_reverse", "follows", ["followed_id", "follower_id"])

    # ══════════════════════════════════════════════════════════════════════
    # 3. CONTRIBUTORS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "contributors",
        sa.Column("contributor_id", UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("bio", sa.Text, nullable=True),
        sa.PrimaryKeyConstraint("contributor_id"),
    )
    op.create_index("ix_contributors_name", "contributors", ["name"])

    # ══════════════════════════════════════════════════════════════════════
    # 4. BOOKS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "books",
        sa.Column("book_id", UUID(as_uuid=True), nullable=False),
        sa.Column("external_api_id", sa.String(64), nullable=False),
        sa.Column("isbn_13", sa.String(13), nullable=True),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("published_date", sa.Date, nullable=True),
        sa.Column("edition", sa.String(100), nullable=True),
        sa.Column("publishing_location", sa.String(200), nullable=True),
        sa.Column(
            "is_active", sa.Boolean, server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "search_vector",
            TSVECTOR,
            sa.Computed("to_tsvector('english', coalesce(title, ''))", persisted=True),
            nullable=True,
        ),
        sa.Column("log_count", sa.Integer, server_default=sa.text("0"), nullable=False),
        sa.Column("avg_rating", sa.Numeric(3, 2), nullable=True),
        sa.Column(
            "currently_reading_count",
            sa.Integer,
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("book_id"),
        sa.UniqueConstraint("external_api_id"),
        sa.UniqueConstraint("isbn_13"),
    )
    op.create_index("ix_books_title", "books", ["title"])
    op.create_index(
        "ix_books_search", "books", ["search_vector"], postgresql_using="gin"
    )
    op.create_index(
        "ix_books_popular", "books", ["is_active", sa.text("log_count DESC")]
    )
    op.create_index(
        "ix_books_top_rated",
        "books",
        ["is_active", sa.text("avg_rating DESC")],
        postgresql_where=sa.text("avg_rating IS NOT NULL"),
    )
    op.create_index(
        "ix_books_trending",
        "books",
        ["is_active", sa.text("currently_reading_count DESC")],
    )

    # ══════════════════════════════════════════════════════════════════════
    # 5. BOOK_CONTRIBUTORS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "book_contributors",
        sa.Column("book_id", UUID(as_uuid=True), nullable=False),
        sa.Column("contributor_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "AUTHOR",
                "ILLUSTRATOR",
                "TRANSLATOR",
                "EDITOR",
                "FOREWORD_BY",
                "NARRATOR",
                name="contributor_role_enum",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("book_id", "contributor_id", "role"),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["contributor_id"], ["contributors.contributor_id"], ondelete="CASCADE"
        ),
    )

    # ══════════════════════════════════════════════════════════════════════
    # 6. READING_STATUSES
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "reading_statuses",
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("book_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WANT_TO_READ",
                "READING",
                "READ",
                "DID_NOT_FINISH",
                name="reading_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "book_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"], ondelete="RESTRICT"),
    )
    op.create_index(
        "ix_reading_status_user_status", "reading_statuses", ["user_id", "status"]
    )
    op.create_index("ix_reading_status_book", "reading_statuses", ["book_id"])

    # ══════════════════════════════════════════════════════════════════════
    # 7. BOOK_ENTRIES
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "book_entries",
        sa.Column("entry_id", UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("book_id", UUID(as_uuid=True), nullable=False),
        sa.Column("rating", sa.SmallInteger, nullable=True),
        sa.Column("review_text", sa.Text, nullable=True),
        sa.Column(
            "is_spoiler", sa.Boolean, server_default=sa.text("false"), nullable=False
        ),
        sa.Column("mood", sa.String(50), nullable=True),
        sa.Column(
            "is_deleted", sa.Boolean, server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "logged_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "like_count", sa.Integer, server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "repost_count", sa.Integer, server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "comment_count", sa.Integer, server_default=sa.text("0"), nullable=False
        ),
        sa.PrimaryKeyConstraint("entry_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"], ondelete="RESTRICT"),
        sa.CheckConstraint("rating >= 1 AND rating <= 10", name="ck_rating_range"),
    )
    op.create_index(
        "ix_book_entries_user_created",
        "book_entries",
        ["user_id", sa.text("created_at DESC")],
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index(
        "ix_book_entries_book",
        "book_entries",
        ["book_id"],
        postgresql_where=sa.text("is_deleted = false"),
    )
    op.create_index("ix_book_entries_user_fk", "book_entries", ["user_id"])

    # ══════════════════════════════════════════════════════════════════════
    # 8. LISTS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "lists",
        sa.Column("list_id", UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("list_name", sa.String(150), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column(
            "is_public", sa.Boolean, server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("list_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.UniqueConstraint("user_id", "list_name", name="uq_user_list_name"),
    )
    op.create_index(
        "ix_lists_public_created",
        "lists",
        [sa.text("created_at DESC")],
        postgresql_where=sa.text("is_public = true"),
    )

    # ══════════════════════════════════════════════════════════════════════
    # 9. LIST_ITEMS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "list_items",
        sa.Column("list_id", UUID(as_uuid=True), nullable=False),
        sa.Column("book_id", UUID(as_uuid=True), nullable=False),
        sa.Column("position", sa.Integer, server_default=sa.text("0"), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("list_id", "book_id"),
        sa.ForeignKeyConstraint(["list_id"], ["lists.list_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["book_id"], ["books.book_id"], ondelete="CASCADE"),
    )
    op.create_index("ix_list_items_position", "list_items", ["list_id", "position"])

    # ══════════════════════════════════════════════════════════════════════
    # 10. COMMENTS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "comments",
        sa.Column("comment_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "user_id", UUID(as_uuid=True), nullable=True
        ),  # SET NULL on user delete
        sa.Column("entry_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "path", sa.Text, nullable=False
        ),  # Alembic uses Text; PostgreSQL stores as LTREE via extension
        sa.Column("comment_text", sa.Text, nullable=False),
        sa.Column(
            "is_deleted", sa.Boolean, server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("comment_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["book_entries.entry_id"], ondelete="CASCADE"
        ),
    )
    # Fix the column type to LTREE (Alembic doesn't natively support ltree).
    op.execute("ALTER TABLE comments ALTER COLUMN path TYPE ltree USING path::ltree")
    op.create_index(
        "ix_comments_path_gist", "comments", ["path"], postgresql_using="gist"
    )
    op.create_index("ix_comments_entry", "comments", ["entry_id"])
    op.create_index("ix_comments_user", "comments", ["user_id"])

    # ══════════════════════════════════════════════════════════════════════
    # 11. LIKES
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "likes",
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("entry_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "entry_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["book_entries.entry_id"], ondelete="CASCADE"
        ),
    )
    op.create_index("ix_likes_entry", "likes", ["entry_id"])

    # ══════════════════════════════════════════════════════════════════════
    # 12. REPOSTS
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "reposts",
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("entry_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "entry_id"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["book_entries.entry_id"], ondelete="CASCADE"
        ),
    )
    op.create_index("ix_reposts_entry", "reposts", ["entry_id"])

    # ══════════════════════════════════════════════════════════════════════
    # 13. TIMELINE
    # ══════════════════════════════════════════════════════════════════════
    op.create_table(
        "timeline",
        sa.Column("timeline_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", UUID(as_uuid=True), nullable=False),
        sa.Column("entry_id", UUID(as_uuid=True), nullable=False),
        sa.Column(
            "activity_type",
            sa.Enum(
                "REVIEW",
                "REPOST",
                "STATUS_UPDATE",
                name="activity_type_enum",
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("timeline_id", "created_at"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["entry_id"], ["book_entries.entry_id"], ondelete="CASCADE"
        ),
        sa.UniqueConstraint(
            "user_id", "entry_id", "activity_type", name="uq_timeline_no_dupes"
        ),
    )
    # Covering index with INCLUDE — Alembic doesn't support INCLUDE natively,
    # so we use raw SQL for this one.
    op.execute(
        "CREATE INDEX ix_timeline_user_created ON timeline "
        "(user_id, created_at DESC) INCLUDE (entry_id, activity_type)"
    )
    op.create_index("ix_timeline_entry", "timeline", ["entry_id"])


def downgrade() -> None:
    """Drop everything in reverse order."""
    # Tables (reverse dependency order)
    op.drop_table("timeline")
    op.drop_table("reposts")
    op.drop_table("likes")
    op.drop_table("comments")
    op.drop_table("list_items")
    op.drop_table("lists")
    op.drop_table("book_entries")
    op.drop_table("reading_statuses")
    op.drop_table("book_contributors")
    op.drop_table("follows")
    op.drop_table("books")
    op.drop_table("contributors")
    op.drop_table("users")

    # Enums
    op.execute("DROP TYPE IF EXISTS activity_type_enum")
    op.execute("DROP TYPE IF EXISTS reading_status_enum")
    op.execute("DROP TYPE IF EXISTS contributor_role_enum")

    # Extensions (optional — you might want to keep ltree around)
    # op.execute("DROP EXTENSION IF EXISTS ltree")
